
CREATE TABLE AUTHOR ( 
	id INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1), 
	lastName varchar(50), 
	firstName varchar(50), 
	primary key (id) 
);

CREATE table ARTICLE (
	idArticle INTEGER GENERATED BY DEFAULT AS IDENTITY (start with 1), 
	price INTEGER, 
	description varchar(20), 
	primary key (idArticle)
);

CREATE TABLE BOOK (
	idArticle INTEGER, 
	title varchar(50), 
	ISBN varchar(30), 
	primary key (idArticle), 
	FOREIGN KEY (idArticle) REFERENCES ARTICLE(idArticle)
);

CREATE table ARTIST (
	id INTEGER, 
	name varchar(50), 
	primary key (id)
);

CREATE table STYLE (
	id INTEGER, 
	name varchar(50), 
	primary key (id)
);

CREATE table DISK (
	idArticle INTEGER, 
	idArtist INTEGER, 
	idStyle INTEGER, 
	primary key (idArticle),
	FOREIGN KEY (idArticle) REFERENCES ARTICLE(idArticle), 
	FOREIGN KEY (idArtist) REFERENCES ARTIST(id),
	FOREIGN KEY (idStyle) REFERENCES STYLE(id)
);

CREATE table CATEGORIE(
	id INTEGER,
	nom varchar(50),
	primary key (id)
);

CREATE table REALISATEUR(
	id INTEGER,
	nom varchar(50),
	primary key (id)
);

CREATE table DVD(
	idArticle INTEGER, 
	idCategorie INTEGER, 
	idRealisateur INTEGER, 
	primary key (idArticle),
	FOREIGN KEY (idArticle) REFERENCES ARTICLE(idArticle)
);

CREATE table VEDETTE(
	id INTEGER,
	firstName varchar(50),
	lastName varchar(50),
	primary key (id)
);

CREATE table PLAYED_IN_DVD_VEDETTE(
	idDvd INTEGER,
	idVedette INTEGER,
	primary key (idDvd, idVedette),
	foreign key (idDvd) REFERENCES DVD(idArticle),
	foreign key (idVedette) REFERENCES VEDETTE(id)
);

CREATE TABLE WROTE_BY_AUTHOR_BOOK (
	idBook INTEGER, 
	idAuthor INTEGER, 
	PRIMARY KEY (idBook, idAuthor), 
	FOREIGN KEY (idBook) REFERENCES BOOK(idArticle), 
	FOREIGN KEY (idAuthor) REFERENCES AUTHOR(id)
);

insert into AUTHOR values(100, 'Rowling', 'JK');

insert into ARTICLE values(10, 25, 'Le livre 4 d''Harry Potter');

insert into BOOK values(10, 'Harry Potter et la coupe de feu', '00448U573');

-- un article peut etre un livre, un disque ou un dvd
-- un livre a un ou plusieurs auteurs
-- un cd peut etre realisé par un artiste ou un groupe
-- un cd appartient a un style musical
-- un dvd a une categorie , un realisateur et une ou plusieures vedettes


-- je veux pouvoir recuperer la totalité des oeuvre d'un artiste
-- je veux pouvoir connaitre la somme (prix) des ventes effectuée par categorie d'articles
-- je veux savoir quel style musical connait les meilleures ventes
-- je veux resister à l'injection sql
-- je veux pouvoir mettre à jour le prix des articles
-- les opérations CRUD doivent etre disponible pour chaque table
